package com.ejercicio

import com.ejercicio.clases.Dron

object Main {
  def main(args: Array[String]): Unit = {

    var dron = new Dron()

    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoAbajo("Abajo")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoArriba("Arriba")
    dron.comandoAtras("Atras")
    dron.comandoAtras("Atras")
    dron.comandoAtras("Atras")
    dron.comandoAtras("Atras")
    dron.comandoAtras("Atras")
    dron.comandoDerecha("Derecha")
    dron.comandoDerecha("Derecha")
    dron.comandoDerecha("Derecha")
    dron.comandoDerecha("Derecha")
    dron.comandoIzquierda("Izquierda")
    dron.comandoIzquierda("Izquierda")
    dron.comandoIzquierda("Izquierda")
    dron.comandoAdelante("Adelante")
    dron.comandoAdelante("Adelante")
    dron.comandoAdelante("Adelante")
    dron.comandoAdelante("Adelante")
    dron.comandoAdelante("Adelante")
    dron.comandoAdelante("Adelante")
    dron.comandoAdelante("Adelante")
  }
}
